### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by cdemyanovich** [beccanelson/backbone-ttt#3]
The README instructs to run `testem`, but I have no such command even after running `npm install`. How do I run tests?

**Comment by becca-bailey** [comment]
I added testem to package.json, but I may also need to add instructions to install it globally in the readme. I'll test it out on someone else's computer and let you know.

**Comment by cdemyanovich** [comment]
Aren't these packages best installed locally?

**Comment by cdemyanovich** [comment]
See docs for [`npm install`](https://docs.npmjs.com/cli/install) re: the `--save-dev` option. That's what we do on my project for things like testem.

**Comment by becca-bailey** [comment]
Yes, that's what I did. It should work now!
