### ISSUE TITLE
Can't play in Safari

### ISSUE THREAD

**Issue by cdemyanovich** [beccanelson/backbone-ttt#4]
When I run `open index.html` in my terminal, Safari opens, but I'm unable to play the game. See the attached screenshot.
![backbone-ttt-safari](https://cloud.githubusercontent.com/assets/2271/18398495/a60de52a-7692-11e6-8984-79dce2c46088.png)

**Comment by cdemyanovich** [comment]
I have the same experience in Chrome.

**Comment by becca-bailey** [comment]
You should be able to try again--there was a typo in main.js after I switched it to coffeescript. I should probably come up with some sort of integration test for this...

**Comment by cdemyanovich** [comment]
I'm now able to play the game.
