### ISSUE TITLE
Can Claim Claimed Spaces

### ISSUE THREAD

**Issue by rmulhol** [beccanelson/backbone-ttt#6]
I'm able to take a space that's already taken by the computer, which prevents the game from being unbeatable.
![screen shot 2016-09-12 at 8 44 29 am](https://cloud.githubusercontent.com/assets/7875345/18438446/0230184c-78c7-11e6-99af-95db95fbac34.png)

**Comment by becca-bailey** [comment]
I'm aware of this, and it's something I've been working on--I have all the code in place to disable spots while there is a request in progress, but there's still something wonky going on with an asynchronous callback that re-enables the spots before the request is complete.

**Comment by becca-bailey** [comment]
Also, it doesn't look like this is the latest version--the current one seems to work better.

**Comment by rmulhol** [comment]
Cool, I saw that behavior by clicking the `play now` link in the readme, so maybe the github-pages branch just needs to be updated?

**Comment by becca-bailey** [comment]
Yes, probably!
